version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: leantime_app
    volumes:
      - .:/var/www
    environment:
      LEAN_DB_HOST: db
      LEAN_DB_USER: root
      LEAN_DB_PASSWORD: root
      LEAN_DB_DATABASE: leantime
      LEAN_DB_PORT: 3306
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 5


  web:
    image: nginx:latest
    container_name: leantime_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: leantime_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leantime
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
